server:
  port: 9097
spring:
  profiles:
    active: local
  application:
    name: TaskManagement

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



