server:
  port: 9097

spring:
  application:
    name: TaskManagement

  datasource:
    url: jdbc:postgresql://db:5432/taskmanagement
    username: postgres
    password: pritam@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



